# Generated by Django 4.2.8 on 2024-02-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_handgun', models.CharField(max_length=50)),
                ('price_rifle', models.CharField(max_length=50)),
                ('price_instructor', models.CharField(max_length=50)),
                ('price_handgun_ammo', models.CharField(max_length=50)),
                ('price_rifle_ammo', models.CharField(max_length=50)),
                ('price_site', models.CharField(max_length=50)),
            ],
        ),
    ]
