# Generated by Django 4.2.8 on 2024-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.FileField(blank=True, upload_to='shooting_range_images'),
        ),
    ]
