# Generated by Django 4.2.8 on 2024-01-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0002_description_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='image',
        ),
    ]
