# Generated by Django 4.2.8 on 2024-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0003_remove_description_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
