# Generated by Django 4.2.8 on 2024-01-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0004_carouselitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
