# Generated by Django 5.0 on 2023-12-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.FileField(blank=True, upload_to='weapons_images'),
        ),
    ]
