# Generated by Django 5.0 on 2023-12-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_weapon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_types',
            field=models.ManyToManyField(related_name='weapons', to='weapons.weapontype'),
        ),
    ]
